### ISSUE TITLE
not using gpu

### ISSUE THREAD

**Issue by xxopenxx** [Djdefrag/QualityScaler#76]
Hi, it's using 100% of my cpu and 0% of gpu all the time, memory is 0.0gb too

**Comment by SandwichIsGreat** [comment]
What version of python ate you using? This issue can occur when using an outdated python version. I know that Python 3.11.4 works for certain. 3.10 does not work.

**Comment by xxopenxx** [comment]
i have python 3.11.4

**Comment by Djdefrag** [comment]
Hi @xxopenxx.

Are you on Windows 10 or Windows 11? because onnxruntime-directml (the AI engine) is only compatible with this OS.

Otherwhise it will use the CPU

**Comment by xxopenxx** [comment]
Python 3.10.14, I never had problem with any ai open source apps, like stable diffusion, ollama etc

**Comment by Djdefrag** [comment]
@xxopenxx  can you send your PC specs? (Task manager / performance tab)

**Comment by xxopenxx** [comment]
i5 12400f, rtx 4070 12gb vram, 16gb ram

**Comment by Djdefrag** [comment]
Have you installed Visual C Redistributable and DXRuntime?

1. (If not already installed) install Visual-C-Runtimes: 
   - https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

2. (If not already installed) install Directx:
   - https://www.microsoft.com/it-it/download/details.aspx?id=35

typically should already be installed

**Comment by xxopenxx** [comment]
These 2 things already installed

**Comment by Djdefrag** [comment]
Strange, are you sure it is not using your gpu? the temperature is "normal" while upscaling?

Also, if you are on Python, you should see an error that says "onnxruntime will use CPU" in the terminal

**Comment by xxopenxx** [comment]
i dont have that error, there are no errors at all in terminal of quality scaler

**Comment by Djdefrag** [comment]
Are you selecting "High performance" GPU in the options right? and if you select Power saving?

**Comment by SandwichIsGreat** [comment]
> Python 3.10.14, I never had problem with any ai open source apps, like stable diffusion, ollama etc

wait.... do you have python 3.10.14 or 3.11.4? Because this looks an awfully lot like this issue https://github.com/Djdefrag/QualityScaler/issues/69

**Comment by xxopenxx** [comment]
![image](https://github.com/Djdefrag/QualityScaler/assets/22219613/262065fe-dac7-45d3-85de-47123423a420)

**Comment by xxopenxx** [comment]
![image](https://github.com/Djdefrag/QualityScaler/assets/22219613/67c0c856-de5b-4c29-9d84-8981e24d5050)

**Comment by Djdefrag** [comment]
Hi my friend, maibe you do not see the correct "graph". In fact, you are seeing only "Video encode" e "Video decode", but there are more options. To see if the gpu is being used, you have to switch to "3D" graph

**Comment by xxopenxx** [comment]
But while im using stable diffusion and im upscaling photo for example, I have 99% gpu usage in task manager, it's same for ollama and video diffusion. Upscaling using qualityscaler takes 2h to upscale 2minutes video from 360 p to 760p, using multihreading

**Comment by Djdefrag** [comment]
sorry but, just a stupid question, have you installed the correct dependencies in requirements.txt?

**Comment by xxopenxx** [comment]
![image](https://github.com/Djdefrag/QualityScaler/assets/22219613/509fb5ff-8b1a-44df-9b62-520abb05f5da)

**Comment by xxopenxx** [comment]
i can share screen on discord or something like that if you want

**Comment by Djdefrag** [comment]
can you unistall everything and re-install? i think there is some problem somewere because the latest version of onnxruntime-directml is 1.17.3, but you have 1.17.0

- pip freeze > requirements.txt
- pip uninstall -r requirements.txt -y
- pip cache purge

**Comment by lindathomass** [comment]
Can I run it if I don't have GPU ?
If so how long would it take to process lets say a 5 min video on a 8GM RAM (I5 3rd gen) machine ?

**Comment by Djdefrag** [comment]
Hi my friend,

yes, it will run without GPU, but will be really slow.

Maibe you can try using the lightest AI model, RealSR_Gx4

**Comment by pmth** [comment]
Hello - I have the same issue. From both steam app and version 3.6 from github. The symptom is that CPU is peak and no GPU usage (no memory allocation, CUDA is low % (e.g. 0-5% same as GPU).

I found this on stack and tried the script. 
https://stackoverflow.com/questions/64452013/how-do-you-run-a-onnx-model-on-a-gpu

Mine say, "CPU-DML". Is that correct? 

I also check python package and it is using 


```
onnxconverter-common==1.14.0     
onnxruntime-directml==1.18.0     
```

**Comment by pmth** [comment]
ok - some update. installed onnxruntime-gpu and onnxruntime (cpu) and tried to use it. It turned out that estimates say 19hrs+ rather than 30mins with onnxruntime-directml. 

Then, I look at GPU temperature, and temp is a bit higher than usual (70C). So, I guess, task manager may not report the right GPU metrics?

**Comment by Djdefrag** [comment]
> ok - some update. installed onnxruntime-gpu and onnxruntime (cpu) and tried to use it. It turned out that estimates say 19hrs+ rather than 30mins with onnxruntime-directml.
> 
> Then, I look at GPU temperature, and temp is a bit higher than usual (70C). So, I guess, task manager may not report the right GPU metrics?

Hi my friend, yes, with Nvidia GPU Task manager does not visualize "AI processing" by default. You have to select the correct Voice from the graph menu, probably **Compute 0** or **High priority 3D**

**Comment by pmth** [comment]
![image](https://github.com/Djdefrag/QualityScaler/assets/1982067/5edc3d8a-76cf-4128-9a71-d7d1c889ed62)

I couldn't figure out where the bottleneck is. It doesn't use full - cpu or GPU. VRAM is very low as well.

![image](https://github.com/Djdefrag/QualityScaler/assets/1982067/cea327c3-8439-4181-adcd-6c96ed5267a7)

(note: I added hvec_nvenc for faster hardware encoding, using it with P7 still several times faster and I couldn't tell the different between software/hardware for my use case)

**Comment by Djdefrag** [comment]
Hi my friend,

usually Half precision is faster, i reccomend use Full precision only for old gpus (which are not compatible with Half precision).

For Nvidia gpu's, Task Manager does not show GPU usage for AI processing by default. It should show it in one of these graphs, but I don't know which one because I don't have an Nvidia GPU :(

![Immagine 2024-06-22 120428](https://github.com/Djdefrag/QualityScaler/assets/32263112/07ed1f55-d372-4158-90e5-24750fdc96bc)

In any case, it is also useful to look at the GPU temperature, to see if it is being used. If the temperature is high, it means it is being used properly.

**Comment by pmth** [comment]
For me, it shows as Graphic_1 above which is running around 67%. I don't have High priority 3D.
Yeh. I have been playing around with Half precision setting, I settled with half precision.

Do you have recommendation on interpolation? I noticed improvement selecting "None". However, I don't know if it's happening in every frame.

btw, I solved the GPU/CPU not used problem. I made change to allow 6 threads, now GPU goes up around 80%, I think VRAM is 1GB more and CPU is bounded :). It's reduced1.5 hours of 5 hrs processing with 4 threads. I think Real-ESRGAN can use high # of thread setting. But ESRGAN, will burn out my CPU much quicker.

**Comment by wegylexy** [comment]
how about `onnxruntime-gpu`?
